# Dockerfile for Archipelago Discord Bot

FROM python:3.13-slim

# Set working directory
WORKDIR /app

RUN apt-get update && apt-get install -y git

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the Archipelago source code
COPY . /app

# Run the Discord bot
CMD ["python", "DiscordBot.py"]